services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
      
  goapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      HOST: ${HOST}

      POSTGRES_HOST: postgres  # Use service name instead of localhost
      POSTGRES_PORT: 5432      # Use internal container port, not mapped port
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    depends_on:
      - postgres
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data:
  minio_data: